language: python

services:
  - docker

env:
  REACT_APP_USERS_SERVICE_URL: http://127.0.0.1

before_install:
  - pip install docker-compose

before_script:
  - docker-compose up -d --build

script:
  - docker-compose exec users python manage.py test
  - docker-compose exec users flake8 project

after_script:
  - docker-compose down -v
