language: python

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.24.0

before_install:
  - pip install --user docker-compose

before_script:
  - docker-compose -f docker-compose-prod.yml up -d --build

script:
  - docker-compose -f docker-compose-prod.yml exec users python manage.py test
  - docker-compose -f docker-compose-prod.yml exec users flake8 project

after_script:
  - docker-compose -f docker-compose-prod.yml down -v
