FROM node:11.12.0-alpine as builder

WORKDIR /usr/src/app

ARG REACT_APP_USERS_SERVICE_URL
ENV REACT_APP_USERS_SERVICE_URL $REACT_APP_USERS_SERVICE_URL
ARG NODE_ENV
ENV NODE_ENV $NODE_ENV

COPY package.json package.json
COPY yarn.lock yarn.lock
RUN yarn install

COPY . /usr/src/app
RUN npx react-scripts build


FROM nginx:1.15.9-alpine

COPY --from=builder /usr/src/app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]